"""Runtime contracts shared by live acquisition and estimator replay."""

from __future__ import annotations

from importlib import import_module
from typing import Any


_EXPORT_MODULES = {
    "ARTIFACT_INVENTORY_DIGEST_ALGORITHM": "runtime.artifacts",
    "AtomicBundlePublisher": "runtime.artifacts",
    "AdaptiveAbortedEvent": "runtime.adaptive_protocol",
    "AdaptiveBootstrap": "runtime.adaptive_protocol",
    "AdaptiveCandidateSnapshot": "runtime.adaptive_protocol",
    "AdaptiveCandidatesEvent": "runtime.adaptive_protocol",
    "AdaptivePublishedEvent": "runtime.adaptive_protocol",
    "AdaptiveReadyEvent": "runtime.adaptive_protocol",
    "AdaptiveRecordEvent": "runtime.adaptive_protocol",
    "AdaptiveRefineRequest": "runtime.adaptive_protocol",
    "AdaptiveRuntimeSession": "runtime.adaptive",
    "AdaptiveSessionEvent": "runtime.adaptive_protocol",
    "AdaptiveStepRequest": "runtime.adaptive_protocol",
    "parse_adaptive_event": "runtime.adaptive_protocol",
    "serve_adaptive_session": "runtime.adaptive",
    "AdaptiveResumePrefix": "runtime.adaptive_client",
    "AdaptiveProtocolDirection": "runtime.adaptive_client",
    "AdaptiveProtocolObservation": "runtime.adaptive_client",
    "AdaptiveRuntimeClient": "runtime.adaptive_client",
    "candidate_index_for_pose": "runtime.adaptive_client",
    "parse_adaptive_resume_prefix": "runtime.adaptive_client",
    "atomic_copy_file": "runtime.artifacts",
    "atomic_write_bytes": "runtime.artifacts",
    "atomic_write_json": "runtime.artifacts",
    "atomic_write_text": "runtime.artifacts",
    "ArtifactInventory": "runtime.artifacts",
    "build_artifact_inventory": "runtime.artifacts",
    "DurableJSONLWriter": "runtime.artifacts",
    "publish_artifact_manifest": "runtime.artifacts",
    "simulation_runtime_root": "runtime.assets",
    "standard_geant4_config_path": "runtime.assets",
    "CUIDashboardConfig": "runtime.cui",
    "CUIRoute": "runtime.cui",
    "CUIServerHandle": "runtime.cui",
    "CUI_URL_MESSAGE_PREFIX": "runtime.cui",
    "cui_browser_url": "runtime.cui",
    "cui_route_from_records": "runtime.cui",
    "resolve_cui_public_host": "runtime.cui",
    "start_cui_server": "runtime.cui",
    "CUIAcquisitionFrame": "runtime.cui_components",
    "CUIPanelSpec": "runtime.cui_components",
    "CUIScene": "runtime.cui_components",
    "CUIStatus": "runtime.cui_components",
    "CUITruthDisplayMode": "runtime.cui_components",
    "shared_cui_panel_specs": "runtime.cui_components",
    "write_cui_index": "runtime.cui_components",
    "write_cui_status": "runtime.cui_components",
    "CLIJSONEventFraming": "runtime.cli_events",
    "CANONICAL_UNITS": "runtime.forward_model_manifest",
    "ResolvedForwardContext": "runtime.forward_context",
    "FORWARD_CONFORMANCE_CASE_ORDER": "runtime.forward_conformance",
    "FORWARD_CONFORMANCE_SCHEMA_VERSION": "runtime.forward_conformance",
    "FORWARD_CONFORMANCE_UNITS": "runtime.forward_conformance",
    "ForwardConformanceDetectorPose": "runtime.forward_conformance",
    "ForwardConformanceFixture": "runtime.forward_conformance",
    "ForwardConformanceFixtureError": "runtime.forward_conformance",
    "ForwardConformanceObstacle": "runtime.forward_conformance",
    "ForwardConformanceObstacleBox": "runtime.forward_conformance",
    "ForwardConformanceSourcePoint": "runtime.forward_conformance",
    "line_energy_weight_by_isotope": "runtime.forward_model_manifest",
    "production_line_mu_by_isotope": "runtime.forward_model_manifest",
    "MEASUREMENT_LOG_SCHEMA_VERSION": "runtime.measurement_log",
    "MeasurementLog": "runtime.measurement_log",
    "MeasurementLogArrayView": "runtime.measurement_log",
    "MeasurementLogStationView": "runtime.measurement_log",
    "MeasurementLogView": "runtime.measurement_log",
    "MeasurementLogRecord": "runtime.measurement_log",
    "MeasurementStation": "runtime.measurement_log",
    "MeasurementLogStreamWriter": "runtime.measurement_log",
    "MeasurementLogValidationError": "runtime.measurement_log",
    "build_forward_model_manifest": "runtime.measurement_log",
    "load_measurement_log": "runtime.measurement_log",
    "measurement_log_artifact_inventory": "runtime.measurement_log",
    "measurement_log_sha256": "runtime.measurement_log",
    "measurement_records_content_sha256": "runtime.measurement_log",
    "validate_forward_model_manifest": "runtime.measurement_log",
    "write_deterministic_npz": "runtime.measurement_log",
    "write_measurement_log": "runtime.measurement_log",
    "MeasurementLogPrefix": "runtime.prefix",
    "MEASUREMENT_RECORDS_DIGEST_ALGORITHM": "runtime.prefix",
    "STATION_BOUNDARIES_DIGEST_ALGORITHM": "runtime.prefix",
    "covered_station_boundaries_digest": "runtime.prefix",
    "covered_station_boundaries_sha256": "runtime.prefix",
    "materialize_measurement_log_prefix": "runtime.prefix",
    "measurement_records_digest": "runtime.prefix",
    "measurement_records_sha256": "runtime.prefix",
    "DigestIdentity": "runtime.provenance",
    "ConfigIdentity": "runtime.provenance",
    "load_strict_json": "runtime.provenance",
    "strict_canonical_json_bytes": "runtime.provenance",
    "strict_json_loads": "runtime.provenance",
    "strict_sha256_json": "runtime.provenance",
}


def __getattr__(name: str) -> Any:
    """Load public runtime contracts without eager package side effects."""
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Return eager and lazy public package attributes."""
    return sorted(set(globals()) | set(_EXPORT_MODULES))

__all__ = [
    "ARTIFACT_INVENTORY_DIGEST_ALGORITHM",
    "AtomicBundlePublisher",
    "ArtifactInventory",
    "AdaptiveAbortedEvent",
    "AdaptiveBootstrap",
    "AdaptiveCandidateSnapshot",
    "AdaptiveCandidatesEvent",
    "AdaptivePublishedEvent",
    "AdaptiveProtocolDirection",
    "AdaptiveProtocolObservation",
    "AdaptiveReadyEvent",
    "AdaptiveRecordEvent",
    "AdaptiveRefineRequest",
    "AdaptiveResumePrefix",
    "AdaptiveRuntimeClient",
    "AdaptiveRuntimeSession",
    "AdaptiveSessionEvent",
    "AdaptiveStepRequest",
    "CANONICAL_UNITS",
    "CUIAcquisitionFrame",
    "CUIDashboardConfig",
    "CUIPanelSpec",
    "CUIRoute",
    "CUIScene",
    "CUIServerHandle",
    "CUIStatus",
    "CUITruthDisplayMode",
    "CUI_URL_MESSAGE_PREFIX",
    "CLIJSONEventFraming",
    "ConfigIdentity",
    "DigestIdentity",
    "DurableJSONLWriter",
    "FORWARD_CONFORMANCE_CASE_ORDER",
    "FORWARD_CONFORMANCE_SCHEMA_VERSION",
    "FORWARD_CONFORMANCE_UNITS",
    "ForwardConformanceDetectorPose",
    "ForwardConformanceFixture",
    "ForwardConformanceFixtureError",
    "ForwardConformanceObstacle",
    "ForwardConformanceObstacleBox",
    "ForwardConformanceSourcePoint",
    "MEASUREMENT_RECORDS_DIGEST_ALGORITHM",
    "MEASUREMENT_LOG_SCHEMA_VERSION",
    "MeasurementLog",
    "MeasurementLogArrayView",
    "MeasurementLogStationView",
    "MeasurementLogView",
    "MeasurementLogRecord",
    "MeasurementLogStreamWriter",
    "MeasurementLogValidationError",
    "MeasurementLogPrefix",
    "MeasurementStation",
    "ResolvedForwardContext",
    "STATION_BOUNDARIES_DIGEST_ALGORITHM",
    "atomic_copy_file",
    "atomic_write_bytes",
    "atomic_write_json",
    "atomic_write_text",
    "build_artifact_inventory",
    "build_forward_model_manifest",
    "candidate_index_for_pose",
    "covered_station_boundaries_digest",
    "covered_station_boundaries_sha256",
    "cui_browser_url",
    "cui_route_from_records",
    "load_measurement_log",
    "load_strict_json",
    "line_energy_weight_by_isotope",
    "measurement_log_artifact_inventory",
    "measurement_log_sha256",
    "measurement_records_content_sha256",
    "measurement_records_digest",
    "materialize_measurement_log_prefix",
    "measurement_records_sha256",
    "production_line_mu_by_isotope",
    "parse_adaptive_resume_prefix",
    "parse_adaptive_event",
    "shared_cui_panel_specs",
    "publish_artifact_manifest",
    "resolve_cui_public_host",
    "serve_adaptive_session",
    "simulation_runtime_root",
    "standard_geant4_config_path",
    "start_cui_server",
    "strict_canonical_json_bytes",
    "strict_json_loads",
    "strict_sha256_json",
    "validate_forward_model_manifest",
    "write_deterministic_npz",
    "write_cui_index",
    "write_cui_status",
    "write_measurement_log",
]
