"""Shared estimator-neutral runtime and CUI defaults."""

DEFAULT_MAX_SOURCES_PER_ISOTOPE = 5
DEFAULT_RANDOM_SOURCE_COUNT = 3
DEFAULT_RANDOM_SOURCE_INTENSITY_CPS_1M = 1000000.0
DEFAULT_SOURCE_INTENSITY_RANGE_CPS_1M = (300000.0, 2000000.0)
DEFAULT_ENVIRONMENT_MODE = "random"
DEFAULT_FIXED_OBSTACLE_CONFIG = "obstacle_layouts/Ex5_obstacles.json"
DEFAULT_ROBOT_SPEED_M_S = 0.5
DEFAULT_ROTATION_OVERHEAD_S = 0.5
DEFAULT_NO_ROTATION_OVERHEAD_S = 0.0
DEFAULT_MEASUREMENT_TIME_S = 30.0
DEFAULT_CUI_SPLIT_VIEW_DIR = "results/cui_view/latest"
DEFAULT_CUI_SPLIT_VIEW_HOST = "0.0.0.0"
DEFAULT_CUI_SPLIT_VIEW_PORT = 8877


__all__ = [
    "DEFAULT_CUI_SPLIT_VIEW_DIR",
    "DEFAULT_CUI_SPLIT_VIEW_HOST",
    "DEFAULT_CUI_SPLIT_VIEW_PORT",
    "DEFAULT_ENVIRONMENT_MODE",
    "DEFAULT_FIXED_OBSTACLE_CONFIG",
    "DEFAULT_MAX_SOURCES_PER_ISOTOPE",
    "DEFAULT_MEASUREMENT_TIME_S",
    "DEFAULT_NO_ROTATION_OVERHEAD_S",
    "DEFAULT_RANDOM_SOURCE_COUNT",
    "DEFAULT_RANDOM_SOURCE_INTENSITY_CPS_1M",
    "DEFAULT_ROBOT_SPEED_M_S",
    "DEFAULT_ROTATION_OVERHEAD_S",
    "DEFAULT_SOURCE_INTENSITY_RANGE_CPS_1M",
]
